# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieTrackerApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieTrackerApp
  pod 'SwiftLint'
  pod 'Alamofire', '~> 5.4'

  target 'MovieTrackerAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieTrackerAppUITests' do
    # Pods for testing
  end

end
